### ISSUE TITLE
Module Request: LG Commercial TV Control

### ISSUE THREAD

**Issue by nathanroest** [bitfocus/companion-module-requests#10]
Control of Power On/Off, Input Selection and Volume through IP. 

Commands are listed on page 35 of below PDF linked, specifically for SE3D but also applies to other series monitors

https://github.com/bitfocus/companion/files/3449404/ENG.pdf

**Comment by josephdadams** [comment]
I read through the provided protocol, and it looks like it is rs-232 only. That means we won't be able to fulfill this request since we require Ethernet control. @nathanroest you could look into using an ethernet to RS232 device like the ones from Global Cache, which are already supported in Companion. Good luck! If you disagree with this assessment or have further questions, feel free to re-open the issue.
