### ISSUE TITLE
Enttec Open DMX USB Interface

### ISSUE THREAD

**Issue by fpoliveira78** [bitfocus/companion-module-requests#1312]
We have our DMX lights being controlled by the Enttec Open DMX USB Interface but we are not finding the way to connect to the Bitfocus Companion. Can you help us?

https://www.thomann.de/gb/enttec_open_dmx_usb_interface.htm

**Comment by dnmeid** [comment]
Companion supports Artnet. USB Devices like the Enttec interface are not supported and and since Companion is Ethernet centric there is no effort to change this.
You can download e.g. DMXControl https://www.dmxcontrol.de/en/downloads.html for free and build a bridge from Artnet to the Enttec DMX with it. Not the most elegant solution but it works.
Sorry, I can't provide help how to configure DMXControl.
