### ISSUE TITLE
Analog Way AWJ Protocol Variable Inputs for Stream deck plus

### ISSUE THREAD

**Issue by Jbar1812** [bitfocus/companion-module-requests#1560]
I'm not Sure how feasible any of this is but I would like to request that a Variable input feature be added for the Analog way AWJ Protocol module So the nobs on a stream deck+ can be useful for transition time, layer size and layer position.

If the AWJ Protocol can't do this I think companion could achieve this internally (at least for the transition time) by setting the the transitions time Value as a formular that read the current transition time(like what the Button text can do) and adds a nominated time.
Example in the picture attached.

<img width="962" alt="Set transition time" src="https://github.com/user-attachments/assets/94b369d7-5fc8-409a-bf35-1cde6d64bbd2">

**Comment by dnmeid** [comment]
For position and size this will be available with the next version of the connection which is coming very soon.
For the times so far I did not add this because in Companion 3.4 or at least 3.5 we will extend the expression feature to all options.

I'm closing this request here because:
- one part is done and just needs to be released
- one part will not be done in the module but in core
- this is not the right place for feature requests for existing modules, here you should only request new modules
