### ISSUE TITLE
Control Ventuz Runtime with Vicreo or Octopus

### ISSUE THREAD

**Issue by JayPiEs** [bitfocus/companion-module-requests#172]
I find out that with Vicreo Listener keyboard shortcuts doesn't work with a running Ventuz Runtime.

The requirement was to send Shift key (or some other) to Ventuz in which it controls a programmed animation. The shortcut was set in the Ventuz designer.

it would be great to have the ability to control Ventuz with Vicreo or Octopus Listener.

**Comment by JeffreyDavidsz** [comment]
Do you have some more info? Running which version of Companion, Mac or Windows? Shift key alone is most of the time not a good key. Did you got other keys working (try alt/cmd- tab for example). Screenshot of the action. This kind of information is helpful to understand how your config is. And where the issue is coming from

**Comment by josephdadams** [comment]
It looks like this software may support OSC control. I found this: https://www.ventuz.com/support/help/V4_05/Remoting.html

Is that relevant?

**Comment by dnmeid** [comment]
There is a dedicated Ventuz module available now
