### ISSUE TITLE
VoiceMeeter

### ISSUE THREAD

**Issue by stuxcrystal** [bitfocus/companion-module-requests#212]
I'm surprised that I can't see a request for this application but:

Voice-Meeter-Support is missing:
It has both a C-API (https://www.vb-audio.com/Services/developers.htm) and an UDP-based remote API (https://www.vb-audio.com/Voicemeeter/VBANProtocol_Specifications.pdf)

**Comment by josephdadams** [comment]
What are you hoping to do with it in Companion?

**Comment by stuxcrystal** [comment]
I'd like to mute and route my audio using buttons on the stream-deck.

**Comment by vincentymo** [comment]
Agreed! I would love to have this as well! I would also use it for muting and routing.

**Comment by herzogmedia** [comment]
+1 for that. Also beeing able to do gain-adjustments (moving the channel faders) with companion

**Comment by CloudDevAU** [comment]
+1 from me.  Would be super handy.

**Comment by CloudDevAU** [comment]
Actually, as a work around, you can use the VICREO module and the VoiceMeeter hotkeys to acheive this (how I'm using it currently), just a bit more complicated than necessary and has no feedback on what the current settings are unless you can see the VoiceMeeter window.

**Comment by stuxcrystal** [comment]
It would also be nice to control multiple voicemeeter instances over the network.

**Comment by thedist** [comment]
Just to note here, I did attempt to make a Voicemeeter module as I had a client request it, but because the Voicemeeter API requires hooking into their DLL (this is their officially support method), the modules integration with Companion was declined. 

The only way to get a Voicemeeter module added to companion would be to make/distribute an external app that handles communication with Voicemeeter, and the Companion module would simply be proxying actions/feedback through that external app.

**Comment by TheGreyDiamond** [comment]
@stuxcrystal you mentioned that you've made an http server for voicemeeter, maybe we could just write a module to control that. There is also [this server](https://github.com/Mikatux/voicemeeter-api), however it was last touched 2018... The Voicemeeter Api probably didn't change that much, but using deprecated/stale software is not a good idea.....

**Comment by thedist** [comment]
Requiring users to download an additional app that they have to have running to proxy data between Companion and voicemeeter isn't ideal. Additionally an HTTP endpoint wouldn't be particularly performant if you wanted any sort of feedback.

**Comment by TheGreyDiamond** [comment]
I know, however, there is no real other option. We've seen how to direct hooking got rejected. Meaning we need to have a middleware. Or we can go and bother the voice meeter devs for a rest API. Technically we could talk to Voicemeeter via Midi, but that does not seem like an excellent idea...

**Comment by thedist** [comment]
The other option is to wait until Companion allows for loading modules externally. Then it would be possible to load a module that properly integrates with Voicemeeter rather than trying to cobble things together.

**Comment by TheGreyDiamond** [comment]
@josephdadams maybe we can reconsider not allowing hooking into DLLs? What was the initial reason for not allowing it after all?

**Comment by josephdadams** [comment]
Was I the one that declined it?

**Comment by thedist** [comment]
This was a few years ago so I don't recall who was the one who said a module that is hooking into another applications DLL would not be allowed in Companion, I just remember that it was on Slack and was said by someone from the core team and that they recommended using an external application to proxy requests between Companion instead. Because at the time the module was being developed for one of my clients they didn't wish to take the module any further at that point.

Since then I created a more up to date module that I use within my personal builds, it's not something that'd be release ready as knowing it wouldn't be in an official build I only ever gave it the functionality/feedbacks that I specifically need rather than a module that covers everything.

**Comment by josephdadams** [comment]
My comment would be that the DLL solution would only work on Windows and for companion running directly on that computer. So the middleman program would at least enable it to work across the network like most companion modules.

**Comment by thedist** [comment]
Keep in mind that Voicemeeter is a Windows only app, and due to the nature of it being a consumer software audio mixer rather than professional it'd usually only be used in situations where a single machine is running the production anyway rather than distributed across multiple machines on a network. Similar to Discord and how it's module works in that it can only ever connect to a Discord client running on the same machine as Companion, although that using IPC rather than needing to hook into a DLL.

**Comment by qvjester** [comment]
> Keep in mind that Voicemeeter is a Windows only app, and due to the nature of it being a consumer software audio mixer rather than professional it'd usually only be used in situations where a single machine is running the production anyway rather than distributed across multiple machines on a network. Similar to Discord and how its module works in that it can only ever connect to a Discord client running on the same machine as Companion, although that using IPC rather than needing to hook into a DLL.

I would disagree, we had 60 PCs running Voicemeeter for a show a few weeks ago.

**Comment by thedist** [comment]
On that sort of scale you may want to consider more professional solutions than Voicemeeter which is a consumer app.

Your situation is very much the minority, and since in your situation you would need proxies on each of those PCs anyway there's no reason why you couldn't integrate with a proxy app using existing Companion modules such as the HTTP module to send to the proxy app which will send to Voicemeeter.

If the Companion core team would be okay with it one option may be to have the option of either connecting to Voicemeeter locally, or using a proxy if it's a remote machine, as that I'd be interested in upgrading my existing Voicemeeter module for but if the only option is forcing users to use a proxy then that'll be a roadblock for most users.

**Comment by thedist** [comment]
Just to update, with the changes to Companion v3 I recently asked again about having my Voicemeeter module included in Companion and was again told by the core team that they don't want a Voicemeeter module included in Companion.

They did suggestion that Companion v3 will make it easier to load external modules so I may make my module publicly available then, but that definitely doesn't help with discoverability, updating, or user experience.

**Comment by TheGreyDiamond** [comment]
I'm still sour about the core dev team's decision, though I get their reasoning. If you were to publish your module it would be greatly appreciated. Maybe there will be a second market/module store (like an app store) kind of thing for "unloved" modules at some point.

**Comment by josephdadams** [comment]
there is a voicemeeter module so let's turn that frown upside down

**Comment by vburel2018** [comment]
Someone told me on our discord Server you could need some advices about Voicemeeter Remote API or VBAN protocol. Feel free to use the vm-streamer source code example on our github: https://github.com/vburel2018/Voicemeeter-SDK or let me know what i can do for you.
