### ISSUE TITLE
Lightkey

### ISSUE THREAD

**Issue by spencwells12** [bitfocus/companion-module-requests#219]
I'd like to request support for a lighting software called Lightkey. A lot of churches use this to control their lighting systems, and it would be awesome to have a physical controller for firing cues and presets and stuff. Sorry I can't give any helpful information, I don't know how to write code or anything, I just figured this would be the best place to put this request. Thanks!

**Comment by spencwells12** [comment]
https://lightkeyapp.com/content/04-help/manual/Lightkey%20User%20Guide.pdf

Here's a link to the user guide, external control protocols are listed started on page 150. Hopefully that helps a little.

**Comment by spencwells12** [comment]
Lightkey uses the Open Lighting Architecture, an open-source framework by the Open Lighting Project. Here's the link to their Github page.
https://github.com/OpenLightingProject/ola

**Comment by josephdadams** [comment]
@spencwells12 I read the section of the manual on external control. I didn’t see any ethernet protocols listed, only DMX and MIDI. Because it lacks an Ethernet protocol, your only option right now to use it with Companion would be to use MIDI and some kind of translator. A few options:
* Generic OSC module and OSCulator (small cost) to translate OSC to MIDI
.* MIDI Relay module along with the MIDI relay software (free)
* Qlab module and Qlab to send MIDI

Hope this helps!

**Comment by spencwells12** [comment]
Thank you for looking into it, I appreciate the help! I guess I’ll have to
go another route, but that’s ok.

Thanks again!

**Comment by josephdadams** [comment]
I suggest using midi relay with Companion. It’s what I use at my church to control our lighting board. And I wrote midi relay so if you run into problems, I can help. :)
