### ISSUE TITLE
Loupedeck CT

### ISSUE THREAD

**Issue by eMMeCodes** [bitfocus/companion-module-requests#249]
Hello,

i'm a live productions technician (events, fairs, congress, etc...)

and i use vMix Pro alone and with other hardware (Ascender, ATEM, Streamdeck, etc...).

Companion is a great  and useful software and it saves me a lot of headaches. 

I also do A/V post production and recently i got a [**Loupedeck CT**](https://loupedeck.com/en/products/loupedeck-ct) to work with.

It is amazing and it's completely customizable: from the simple shortcut, to complex macros.

It is mainly designed to work for A/V post production, but after a week spent 

to customize it for vMix and others softwares,

i can state that it can works very well for live productions too.

I can assign all shortcuts and use the wheel to change inputs or scrub clip and mark in/out;

use rotary controllers to select channel (push) and adjust audio or select titles 

and overlay them to the program ...

It’s like Streamdeck, but with rotors and wheel.

It will be AMAZING if you will make a module that supports it.

I've sent an email to Loupedeck asking the same.

Their developers’ page states that .NET/C# knowledge is needed.

[Here the Developers link](https://loupedeck.com/en/stories/loupedeck-developer)

Hope you will find a way and will integrate Loupedeck CT, 

because it will fit PERFECTLY in live productions.

Obviously, if you need testers, i’m in.

Thanks,

             eMMe

**Comment by haakonnessjoen** [comment]
Hi,

We have already reverse engineered the protocol of the Loupedeck a while ago, since their SDK (which even wasn't out at the time), is too restricting for us.

But with that being said, Companion isn't really created in a way to support different surfaces other than button matrixes with screens like the stream decks. So companion will not support that device unless someone rewrites a big part of Companion.

However, we did reverse engineer it because we will be creating a paid application that will support Loupedeck and other kinds of surfaces too. But it is too soon to give a release date yet, I am afraid.

I will write down your info, as you will probably like to test that new app when it is ready for testing.

**Comment by eMMeCodes** [comment]
Thank you so much for your reply.

I’m so happy to know that you’re aware and interested in Loupedeck CT.

I’ll wait for news.

Thanks,

             eMMe

**Comment by Hachi05** [comment]
Greetings. Sorry to reopen, but please add me to that list as well! I'm new to decks, and just purchased a Loupedeck -- I'd love to help out bugtesting!

**Comment by jaoustin** [comment]
Hello, I'm also interested, please add me to the list!

**Comment by Zaid2000** [comment]
Hi, I am also waiting for Vmix loupedeck code.
