### ISSUE TITLE
Module request: Dexonsystem 8x4 4K HDBaseT Seamless Matrix Switcher

### ISSUE THREAD

**Issue by Twilly1126** [bitfocus/companion-module-requests#43]
**Describe the feature:**
Module request for control of the Dexonsystem 8x4 4K HDBaseT Seamless Matrix Switcher.

**Is this platform dependent (windows, mac, ..)?**
Yes -Windows

If documentation is required to implement, do you know where to find it?
Attached is the User manual with EXTERNAL PROGRAMMING in section 4.

**Use cases:**
[Manual_8_DIMAX804KC_UsersManual_3.2.1_2018.8.21.pdf](https://github.com/bitfocus/companion/files/2872864/Manual_8_DIMAX804KC_UsersManual_3.2.1_2018.8.21.pdf)

Looking for external control via Companion using stream deck.
User Preset recall
Layout recall
X Y routing
ect.

Thanks

TW

**Comment by McHauge** [comment]
Hey, I just finished a version one module for Dexon Dimax-Pro and Dexon Divip-Pro, and it's now included in Companion 2.0.0, and since this is in the same branch it might work with it. but if not, then I'll take a look at it.

But just to be sure what commands/functions would you like to se other than the first 3 mentioned above?

**Comment by McHauge** [comment]
I made a thing, there is now a module included in the V2.0.0 builds ready for testing, with MD5 hashing and presets.

**Comment by McHauge** [comment]
Just got confirmation, after some testing of the module, and it seems to be working, I'll mark this as done and close this thread, for now, we can open it again if something comes up.

-Andreas
