### ISSUE TITLE
Support for Proclaim by Faithlife?

### ISSUE THREAD

**Issue by Ryknown** [bitfocus/companion-module-requests#600]
Hello. Is there any support for Proclaim by Faithlife? This is presentation software similar to ProPresenter, which is supported by Companion.
Thank you.
Ryknown

**Comment by Ryknown** [comment]
I'll add that Proclaim does now have support in the Elgato Stream Deck.
Uses would be to add a song, Bible verse, play a video, mute audio, un-mute audio, advance slides, skip slides...

**Comment by Ryknown** [comment]
.. synchronize the transition of slides on multiple PC/Mac computers. We have multiple (2) instances of Proclaim running on different machines to serve video/slides to video walls and Led projectors.

**Comment by Cameron-D** [comment]
I think I have this module working now. I'm still waiting to hear back from Faithlife about proper remote access to the API so I'm not going to ask to have this module made official in Companion just yet.

To start with, I made a tiny single-purpose proxy to access the Proclaim API from a remote computer so I could actually get development underway: https://github.com/Cameron-D/proclaim-proxy (Turns out this was literally two lines of Go!). I've not yet actually tried this in production, but don't see why it wouldn't work.

Then there's the Companion module itself, currently at: https://github.com/Cameron-D/companion-module-faithlife-proclaim

It seems to work quite well in my at-home testing, but I definitely need to take it through some more thorough tests before I'd be happy to call it done and request it be made official.

Currently has support for next/prev slide and item, jumping to specific song parts (verse X, chorus Y, etc.), on/off air and feedback/variable for on-air state. This seems to be everything (and more) that the official StreamDeck plugin supports.

**Comment by Ryknown** [comment]
This is amazing, @Cameron-D !
Thank you!

**Comment by Cameron-D** [comment]
Just to update - Received a response that they'd moved my request to their feedback site (which I wasn't aware of until then), perhaps having some interest shown there will help:
https://feedback.faithlife.com/boards/faithlife-proclaim/posts/stream-deck-proclaim

Either way I plan on doing some proper testing of the module when I find the time, to at least get that half of everything complete.

**Comment by Ryknown** [comment]
Thank you! I have up-voted it!

Ryan
________________________________

**Comment by cpuguru07** [comment]
While not directly related to this Companion module, users interested in this module may also be interested in this request on the Proclaim Feedback Forum to add support for URI cues (so Proclaim can trigger Companion buttons): https://feedback.faithlife.com/boards/faithlife-proclaim/posts/uri-cue-item

**Comment by JordanSjodinFaithlife** [comment]
@Cameron-D thanks for your work here! I'm thinking of adding a simple password that can be configured in Proclaim. And then allow access to outside localhost when that password is sent in a header or something. How's that sound? Seems maybe easier than doing an ip whitelist (in case the IP addresses change)

**Comment by Cameron-D** [comment]
@JordanSjodinFaithlife Something like that sounds like it would work well.

**Comment by JordanSjodinFaithlife** [comment]
We just release the new update (3.2.0.0038 or greater)with a slightly reworked Remote settings that allows you to specify a password. 

We also made some documentation to go along with it! 

https://support.faithlife.com/hc/en-us/articles/4972373093005

**Comment by josephdadams** [comment]
https://github.com/bitfocus/companion-module-requests/issues/773#issuecomment-1093003185

**Comment by cpuguru07** [comment]
Really interested in this module; it seems like it shouldn't be difficult to build - Proclaim is a free download (can be used for free with watermark) and the API is well-documented. In the meantime, I'm using the Generic HTTP module to issue GET commands. Haven't been able to figure out how to retrieve the proclaimAuthToken, but was able to retrieve it manually and store it in a custom variable.

**Comment by josephdadams** [comment]
@cpuguru07 https://github.com/bitfocus/companion/wiki/Module-Development if you want to get started!

**Comment by hussra** [comment]
I've been working on a Companion 3.x module for Proclaim, for which the work by @Cameron-D was a huge help. So far it is working well in my testing (on Companion 3.1.2 on a 4GB Raspberry Pi 4) but could do with me doing a bit more testing.

**Comment by hussra** [comment]
https://github.com/bitfocus/companion-module-logos-proclaim

**Comment by hussra** [comment]
A Proclaim module is now in the Companion 3.2 beta releases.

(Unfortunately it looks like there was a problem with the Companion nightly builds overnight, and only the Windows version of 3.2.0+6622 is so far available on https://user.bitfocus.io/download)
