### ISSUE TITLE
Module Request: MIDI Module

### ISSUE THREAD

**Issue by cxselph** [bitfocus/companion-module-requests#81]
**Describe the feature**
I would love a MIDI module that uses Mac OS X midi network/iac module or rtpmidi on a pc to send midi commands locally or over the network.

Midi Note On/Midi Note Off
Channel/Note/Intensity

Choose connection based on settings in Audio Midi Setup for OS X and similar from pc.
<img width="735" alt="screen shot 2018-06-22 at 3 18 42 pm" src="https://user-images.githubusercontent.com/14942903/41795101-9e69bb16-762f-11e8-8e8e-6fe8922ed919.png">

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**

**Usecases** 
I would use to fire tracks in protools or Ableton live from FOH. Also would be helpful for Renewed visions Propresenter too to control presentations, clear graphics, etc... Lots of other great uses too.

**Comment by BlackScreen** [comment]
Any news on this? I would love this feature also.

**Comment by MeestorX** [comment]
Did you already try MIDI Relay?
https://github.com/bitfocus/companion-module-techministry-midirelay

**Comment by BlackScreen** [comment]
No, I did not. But I will. Thanks for the tip!

**Comment by RobbieBott** [comment]
+1

**Comment by RickDDD** [comment]
+1
Yes, I know MIDI Relay, but Core MIDI is integrated and ready to use in MAC OS and iOS for years and the PC version of it represented by rtpMIDI is also established since many years and THE way to go when using MIDI over network in studios.
It also has a proper GUI.
Sending MIDI from Companion would be the most important part of course, but feedback to press/depress buttons in 
Companion with MIDI notes and MIDI CC would be very nice, too.
So my point is not about much new functionality, but using THE (open) standard for MAC&PC to do it. 

[https://developer.apple.com/documentation/coremidi/](url)
[http://www.tobias-erichsen.de/software/rtpmidi.html](url)
[http://www.tobias-erichsen.de/software/librtpmidi.html](url)

**Comment by lnswlrd** [comment]
+1
Midi over ethernet (CoreMIDI / rtpmidi) would give lots of possibilities.

**Comment by deewhitewolf** [comment]
+1
I don't understand how this isn't already in there.  Currently i've been using the native midi functionality in the stream deck software because companion doesn't support it. If we had this I could use companion on it's own.

**Comment by nic** [comment]
+1

**Comment by Regemark** [comment]
Midi relay is great for people usig Mac, I know someoene who has used it before, however we run a full Windows setup at church and having this function implemented we wouldn't need to run any other pieces of software for control. At the moment we are running RTP Midi to send notes from our presentation pc running Faithlife Proclaim converting the messages to OSC using Central control ($50 btw) just so we can run our Streamdeck as the primary device for control. We also want to be able to control the presentation from the streamdeck using midi control and doing so by bypassing Central control which really isn't a good software in my opinion

**Comment by josephdadams** [comment]
Could you use midi relay on Windows?

**Comment by MeestorX** [comment]
Please try the generic-midi module. It works with rtpMIDI on all platforms.

(@josephdadams you can probably close this issue...)
